import './globals.css'
// import Header from '@/components/layout/Header/header'
import Footer from '@/components/layout/Footer/footer';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ overflowX: "hidden" }}>
        {/* <Header /> */}
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
